# Generated by Django 5.2.6 on 2025-09-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='desciption',
        ),
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
