# Generated by Django 5.2.6 on 2025-09-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('global_system', '0002_remove_food_desciption_food_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_price',
            new_name='price',
        ),
    ]
