# Generated by Django 5.2.6 on 2025-10-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_system', '0007_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='food',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
